apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-master-config
  labels:
    name: prometheus-master-config
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 10s

    rule_files:
      - /etc/prometheus/prometheus.rules

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.localhost"

    scrape_configs:
    - job_name: dc_prometheus
      honor_labels: true
      metrics_path: /federate
      params:
        match[]:
        - '{job=~".+"}'
      static_configs:
        - targets:
          - "10.103.39.181:9090"
