apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: monitoring
spec:
  storageClassName: local-storage
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana"
