apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-ilm
  namespace: logging
data:
  entrypoint.sh: |
    #!/bin/sh

    # create ilm 
    curl -X PUT "http://elasticsearch.logging.svc:9200/_ilm/policy/kube-logs" -H'Content-Type: application/json' -d '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"3d","max_size":"10gb"}}},"delete":{"min_age":"1d","actions":{"delete":{}}}}}}'
    curl -X PUT "http://elasticsearch.logging.svc:9200/_ilm/policy/dee-logs" -H'Content-Type: application/json' -d '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"3d","max_size":"10gb"}}},"delete":{"min_age":"1d","actions":{"delete":{}}}}}}'  
    curl -X PUT "http://elasticsearch.logging.svc:9200/_ilm/policy/monitoring-logs" -H'Content-Type: application/json' -d '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"3d","max_size":"10gb"}}},"delete":{"min_age":"1d","actions":{"delete":{}}}}}}'  
    curl -X PUT "http://elasticsearch.logging.svc:9200/_ilm/policy/logging-logs" -H'Content-Type: application/json' -d '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"3d","max_size":"10gb"}}},"delete":{"min_age":"1d","actions":{"delete":{}}}}}}'  

    #create data views
    curl -X POST "kibana.logging.svc:5601/api/index_patterns/index_pattern" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '{ "override": true,"index_pattern": { "title": "logging-*"}}'
    curl -X POST "kibana.logging.svc:5601/api/index_patterns/index_pattern" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '{ "override": true,"index_pattern": { "title": "kube-system-*" }}'
    curl -X POST "kibana.logging.svc:5601/api/index_patterns/index_pattern" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '{ "override": true,"index_pattern": { "title": "dee-*" }}'
    curl -X POST "kibana.logging.svc:5601/api/index_patterns/index_pattern" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '{ "override": true,"index_pattern": { "title": "ingress-nginx-*" }}'
    curl -X POST "kibana.logging.svc:5601/api/index_patterns/index_pattern" -H 'kbn-xsrf: true' -H 'Content-Type: application/json' -d '{ "override": true,"index_pattern": { "title": "monitoring-*" }}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <system>
      <log>
        format json
        time_format %Y-%m-%d
      </log>
    </system>
    @include kubernetes.conf
    @include this_node.conf
  
  this_node.conf: |  
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file fluentd-docker.pos
      read_from_head true
      tag kubernetes.*
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_type string
          time_format "%Y-%m-%dT%H:%M:%S.%NZ"
          keep_time_key false
        </pattern>
        <pattern>
          format regexp
          expression /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
          time_format '%Y-%m-%dT%H:%M:%S.%N%:z'
          keep_time_key false
        </pattern>
      </parse>
    </source>

    <filter kubernetes.var.log.containers.**.log>
      @type kubernetes_metadata
    </filter>
    
    <match kubernetes.var.log.containers.**.log>
     # @type file
     # path /logs/${record["kubernetes"]["pod_name"]}
      @type stdout     
      format json
    </match>

  system.conf: |
    <match fluent.**>
      @type copy
      <store>
        @type elasticsearch
        host "#{ENV['ELASTICSEARCH_HOST']}"
        port "#{ENV['ELASTICSEARCH_PORT']}"
        user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
        password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
        scheme http
        logstash_format true
        logstash_prefix fluentd-info
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        <buffer>
           flush_interval 5s
        </buffer>
      </store>
      <store>
        @type stdout
      </store>
    </match>

  kubernetes.conf: |
    <source>
      @type forward
      port 9880
      bind 0.0.0.0
    </source>

    <match dee>
      @type copy
      <store>
      @type elasticsearch
      @log_level info
      @id dee
      with_transporter_log true

      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USER']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      default_elasticsearch_version 8
      verify_es_version_at_startup true
      scheme http

      rollover_index true
      template_name dee-logs
      template_file /fluentd/etc/dee-logs.mapping
      logstash_format true
      logstash_prefix ${tag}
      include_tag_key true
      type_name access_log
      tag_key @log_name

      enable_ilm true
      ilm_policy {}
      ilm_policy_id dee-logs

      log_es_400_reason true
      reconnect_on_error true
      reload_on_failure true
      reload_connections false
      <buffer>
          @type file
          path /var/log/fluent/dee-logs.*.buffer
          flush_interval 5s
      </buffer>
     </store>
     </match>


    <match kube-system logging ingress-nginx>
      @type copy
      <store> 
      @type elasticsearch
      @log_level info
      @id system
      with_transporter_log true
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USER']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      default_elasticsearch_version 8
      verify_es_version_at_startup true
      scheme http
      rollover_index true
      template_name kube-logs
      template_file /fluentd/etc/kube-logs.mapping
      logstash_format true
      logstash_prefix ${tag}
      include_tag_key true
      type_name access_log
      tag_key @log_name
      enable_ilm true
      ilm_policy {}
      ilm_policy_id kube-logs
      log_es_400_reason true
      reconnect_on_error true
      reload_on_failure true
      reload_connections false
      <buffer>
          @type file
          path /var/log/fluent/kube-logs.*.buffer
          flush_interval 5s
      </buffer>
     </store>
     </match>

  kube-logs.mapping: |
    {
       "index_patterns": [
         "kube-system*",
         "ingress-nginx*",
         "logging*",
         "monitoring*"
       ],                   
       "template": {
          "settings": {
            "number_of_shards": 1,
            "number_of_replicas": 1,
            "index.lifecycle.name": "kube-logs"     
          } 
        }
    } 

  dee-logs.mapping: |
    {
       "index_patterns": [
         "dee*"
       ],
       "template": {
          "settings": {
            "number_of_shards": 1,
            "number_of_replicas": 1,
            "index.lifecycle.name": "dee"
          } 
        }
    }

