apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <system>
      <log>
        format json
        time_format %Y-%m-%d
      </log>
    </system>
    @include kubernetes.conf
  
  system.conf: |
    <match fluent.**>
      @type copy
      <store>
        @type elasticsearch
        host "#{ENV['ELASTICSEARCH_HOST']}"
        port "#{ENV['ELASTICSEARCH_PORT']}"
        user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
        password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
        scheme http
        logstash_format true
        logstash_prefix fluentd-info
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        <buffer>
           flush_interval 5s
        </buffer>
      </store>
      <store>
        @type stdout
      </store>
    </match>

  kubernetes.conf: |
    <source>
      @type forward
      port 9882
      bind 0.0.0.0
    </source>
 
    <match *.**>
      @type copy
      <store>
        @type elasticsearch
        host elasticsearch.logging.svc
        port 9200
        user "#{ENV['ELASTICSEARCH_USER']}"
        password "#{ENV['ELASTICSEARCH_PASSWORD']}"  
        scheme http
        logstash_format true
        logstash_prefix logging
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        <buffer>
            flush_interval 5s
        </buffer>
      </store>

      <store>
         @type stdout
      </store>
     </match>
