apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        imagePullPolicy: IfNotPresent
#        image: fluent/fluentd:edge-debian
        image: docker-logging_fluentd:latest
        env:
          - name: ELASTICSEARCH_USER
            valueFrom: 
              secretKeyRef: 
                key: username
                name: elasticsearch-creds
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: elasticsearch-creds
          - name:  ELASTICSEARCH_HOST
            value: "elasticsearch.logging.svc"
          - name:  ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
#        resources:
#          limits:
#            memory: 512Mi
#          requests:
#            cpu: 100m
#            memory: 200Mi
        ports:
         - containerPort: 9881
        volumeMounts:
         - name: fluentd-config
           mountPath: /fluentd/etc
#      terminationGracePeriodSeconds: 30
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config
