apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      initContainers:
      - name: elastic-init
        image: yauritux/busybox-curl
        imagePullPolicy: IfNotPresent
        command: ["/bin/entrypoint.sh"]
        volumeMounts:
        - name: fluentd-ilm
          mountPath: /bin/entrypoint.sh
          readOnly: true
          subPath: entrypoint.sh
      containers:
      - name: fluentd
        imagePullPolicy: IfNotPresent
#        image: fluent/fluentd:edge-debian
        image: test_fluent:latest
        env:
          - name: ELASTICSEARCH_USER
            valueFrom: 
              secretKeyRef: 
                key: username
                name: elasticsearch-creds
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: elasticsearch-creds
          - name:  ELASTICSEARCH_HOST
            value: "elasticsearch.logging.svc"
          - name:  ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
#        resources:
#          limits:
#            memory: 512Mi
#          requests:
#            cpu: 100m
#            memory: 200Mi
        ports:
        - containerPort: 9881
        volumeMounts:
        - name: logs
          mountPath: /logs
        - name: fluentd-config
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: fluentd-ilm
        configMap:
          defaultMode: 0700
          name: fluentd-ilm
      - name: logs
        persistentVolumeClaim:
          claimName: fluentd
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers

