apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <system>
      <log>
        format json
        time_format %Y-%m-%d
      </log>
      log_level fatal
    </system>

    @include system.conf
    @include kubernetes.conf

  system.conf: | 
    <label @FLUENT_LOG>
    <filter fluent.**>
      @type grep
      <regexp>
        key @log_name    
        pattern (info|warn|error|fatal)
      </regexp>
    </filter>

    <match fluent.**>
      @type copy
      <store>
        @type elasticsearch
        host elasticsearch.logging.svc
        port 9200
        user elastic
        password changeme
        scheme http
        logstash_format true
        logstash_prefix fluentd_info
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        <buffer>
           flush_interval 5s
        </buffer>
      </store>
      <store>
        @type stdout
      </store>
    </match>
    </label>
  
  kubernetes.conf: |
    <source>
      @type forward
      port 9880
      bind 0.0.0.0
    </source>

    <match *.**>
      @type copy
      <store>
        @type elasticsearch
        host elasticsearch.logging.svc
        port 9200
        user elastic
        password changeme
        scheme http
        logstash_format true
        logstash_prefix kubernetes
        logstash_dateformat %Y%m%d
        include_tag_key true
        type_name access_log
        tag_key @log_name
        <buffer>
            flush_interval 5s
        </buffer>
      </store>
 
      <store>
         @type stdout
      </store>
     </match>
