apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fluentd
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: fluentd.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fluentd
            port:
              number: 9292
  - host: fluentd-logs.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fluentd
            port:
              number: 9880
 
