apiVersion: v1
kind: PersistentVolume
metadata:
  name: fluentd
  namespace: logging
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/fluentd"
