apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
