#apiVersion: v1
#kind: Service
#metadata:
#  name: fluentd-ui
#  namespace: logging
#spec:
#  ports:
#    - port: 9292
#      targetPort: ui
#  selector:
#    app: fluentd
#---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
spec:
  selector:
    app: fluentd
  ports:
    - port: 9880
      targetPort: 9880
      name: test
    - port: 9881
      targetPort: 9881
      name: test1
    - port: 9882
      targetPort: 9882
      name: test2
