apiVersion: v1
kind: Service
metadata:
  name: fluentd-ui
  namespace: logging
spec:
  ports:
    - port: 9292
      targetPort: ui
  selector:
    app: fluentd
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: logging
spec:
  selector:
    app: fluentd
  ports:
    - port: 9880
      targetPort: 9880
      
