#apiVersion: networking.k8s.io/v1
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
#    kubernetes.io/tls-acme: "true"
#    ingress.kubernetes.io/force-ssl-redirect: "true"
  name: kibana
  namespace: logging 

spec:
  rules:
  - host: kibana.localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: kibana
          
#          service: 
#            name: kibana
#            port:
#              number: 5601
