apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/rewrite-target: /$1
#    kubernetes.io/tls-acme: "true"
#    ingress.kubernetes.io/force-ssl-redirect: "true"
  name: kibana
  namespace: logging 
spec:
  rules:
  - host: kibana.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
