apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch
  namespace: logging
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    ## X-Pack settings
    ## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
    #
    xpack.license.self_generated.type: basic
    xpack.security.enabled: false
    cluster.name: full-stack-cluster
    node.name: node-1
    path.data: /data
    http:
      host: 0.0.0.0
      port: 9200
    bootstrap.memory_lock: true
    transport.host: 127.0.0.1
